baseURL = "https://security.science/"
languageCode = "en-us"
title = "THI Cybersecurity Research Group"
disableKinds = [ "section", "taxonomy" ]
ignoreErrors = ["error-disable-taxonomy"]
theme = [ "hugo-snap-gallery", "hugo-cloak-email" ]

[markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.parser.attribute]
    block = true

[menus]
  [[menus.main]]
    name = 'Members'
    URL = '#members'
    weight = 30
  [[menus.main]]
    name = 'Career'
    URL = '#open-positions'
    weight = 40
  [[menus.main]]
    name = 'Code'
    URL = 'code'
    weight = 50

