baseURL = "https://security.science/"
languageCode = "en-us"
title = "THI Cybersecurity Research Group"
disableKinds = [ "taxonomy" ]
ignoreErrors = ["error-disable-taxonomy"]
theme = [ "hugo-snap-gallery", "hugo-cloak-email" ]

[security]
  enableInlineShortcodes = true

[markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.parser.attribute]
    block = true

[menus]
  [[menus.main]]
    name = 'Members'
    URL = '#members'
    weight = 30
